### ISSUE TITLE
a bug that can't hold the camera

### ISSUE THREAD

**Issue by park9379** [potatocs-ce/potatocs-ce-meeting-server#6]
Sometimes when I attend a meeting, I can't catch the camera

**Comment by potatocs-ce** [comment]
If the camera is not functioning properly, it could potentially be a hardware issue. 

When you first enter the page, you have the option to check your device connections, so please ensure they are properly verified.

 If the camera still does not work, there is a possibility that your OS or browser may not be up to date. 
 Lastly, there could be issues with the media server. The media server operates smoothly in an HTTPS environment, so consider purchasing a domain to test this.

**Comment by park9379** [comment]
Thank you.
